germanolleunlp/spotify-browser

client/src/components/Button.js
client/src/components/LikeButton.js
client/src/components/Modal.js
client/src/components/SearchResultItem.js
client/src/components/TrackRow.js

Show modal when clicks on like button
Ticket: https://trello.com/c/10ckhf80

Added modal to add to favorites

---

client/src/components/ArtistTopTracks.js
client/src/components/LikeButton.js
client/src/components/SearchResultItem.js
client/src/components/TrackRow.js
client/src/components/Tracks.js
client/src/redux/actions.js
client/src/redux/reducers.js
client/src/redux/types.js

Add track to favorite list and hide the like button in
search results and top tracks section
Ticket: https://trello.com/c/dEcxhoqU

Add track to favorite and hide like button when its there

---

client/src/components/Albums.js
client/src/components/Alert.js
client/src/components/Artists.js
client/src/components/LikeButton.js
client/src/components/Welcome.js
client/src/redux/actions.js
client/src/redux/reducers.js
client/src/redux/types.js

Show alert when a track is added in my favorite list
Ticket: https://trello.com/c/ytfPrNh5

Added alert component

---

client/src/components/Albums.js
client/src/components/Alert.js
client/src/components/ArtistTopTracks.js
client/src/components/Artists.js
client/src/components/Button.js
client/src/components/LikeButton.js
client/src/components/Modal.js
client/src/components/SearchResultItem.js
client/src/components/TrackRow.js
client/src/components/Tracks.js
client/src/components/Welcome.js
client/src/redux/actions.js
client/src/redux/reducers.js
client/src/redux/types.js

Add to favorites features:
https://trello.com/c/PgebyFUw
https://trello.com/c/10ckhf80
https://trello.com/c/dEcxhoqU
https://trello.com/c/ytfPrNh5

Deploy to production

---

client/src/components/ArtistTopTracks.js
client/src/components/DislikeButton.js
client/src/components/LikeButton.js
client/src/components/SearchResultItem.js
client/src/components/TrackRow.js

Ticket: https://trello.com/c/2uuuLcih

Show trash icon when a track is in my list of favorites

---

client/src/components/Alert.js
client/src/components/DislikeButton.js
client/src/components/LikeButton.js
client/src/components/SearchResultItem.js
client/src/components/TrackRow.js
client/src/theme.js

Ticket: https://trello.com/c/QASoXJQS

Show confirm modal when remove from favorites

---

client/src/components/DislikeButton.js
client/src/components/LikeButton.js
client/src/redux/actions.js
client/src/redux/reducers.js
client/src/redux/types.js

Ticket: https://trello.com/c/6BQudH1i

Remove track from fav

---

client/src/components/DislikeButton.js

Ticket: https://trello.com/c/9oh312vD

Show alert when remove track from list

---

client/src/components/Alert.js
client/src/components/ArtistTopTracks.js
client/src/components/DislikeButton.js
client/src/components/LikeButton.js
client/src/components/SearchResultItem.js
client/src/components/TrackRow.js
client/src/redux/actions.js
client/src/redux/reducers.js
client/src/redux/types.js
client/src/theme.js

* https://trello.com/c/2uuuLcih
* https://trello.com/c/QASoXJQS
* https://trello.com/c/6BQudH1i
* https://trello.com/c/9oh312vD

Deploy to Production 2

---

client/src/components/SearchContent.js
client/src/components/SearchInput.js
client/src/components/Welcome.js

Ticket: https://trello.com/c/muDF8Yll

Added button to link to favorites

---

client/src/Main.js
client/src/components/ArtistTopTracks.js
client/src/components/LikeButton.js
client/src/components/SearchResultItem.js
client/src/components/TrackRow.js
client/src/components/Tracks.js
client/src/components/Welcome.js
client/src/pages/FavoritesPage.js
client/src/redux/reducers.js
client/src/routes.js

Ticket: https://trello.com/c/znTmlTOi

Added fav page

---

client/src/components/Welcome.js
client/src/pages/FavoritesPage.js

Ticket: https://trello.com/c/eLErcoAN

Fixed fav page allignment and added back button

---

client/src/components/Button.js
client/src/components/DislikeButton.js
client/src/components/LikeButton.js
client/src/components/Modal.js
client/src/pages/ArtistPage.js
client/src/theme.js

Ticket: https://trello.com/c/kkG7o1SC

Rebranding buttons

---

client/src/Main.css
client/src/components/SearchResultImage.js
client/src/theme.js

Ticket: https://trello.com/c/duoGptFy

Updated colors

---

client/src/components/ArtistTopTracks.js
client/src/components/FavButton.js
client/src/components/SearchResultItem.js
client/src/components/TrackRow.js
client/src/components/Tracks.js

Ticket: https://trello.com/c/7qysavdK

Add fav button

---

client/src/components/ArtistTopTracks.js
client/src/components/FavButton.js
client/src/redux/actions.js
client/src/redux/reducers.js
client/src/redux/types.js

Ticket: https://trello.com/c/ARjFS2zt

Add to fav

---

client/src/components/Alert.js
client/src/components/FavButton.js
client/src/components/TrackRow.js
client/src/components/Welcome.js
client/src/pages/StyleGuidePage/AlertGuide/AlertGuide.js
client/src/redux/actions.js
client/src/redux/reducers.js
client/src/redux/types.js

Ticket: https://trello.com/c/M7Qn4VEk

Show alert message when add track to fav

---

client/src/components/SearchResultItem.js
client/src/components/TrackRow.js
client/src/components/UnfavButton.js

Ticket: https://trello.com/c/sgvjB4M7

Show unfav button when track is in fav

---

client/src/components/UnfavButton.js

Ticket: https://trello.com/c/F5zUotRY

Show confirm modal when remove from fav

---

client/src/components/UnfavButton.js
client/src/redux/actions.js
client/src/redux/reducers.js
client/src/redux/types.js

Ticket: https://trello.com/c/JYEVv5Cf

Remove from favs

---

client/src/Main.js
client/src/components/Welcome.js
client/src/pages/FavoritesPage.js
client/src/routes.js

Ticket: https://trello.com/c/oXKdqwhu

Add fav page
